{
  "openapi": "3.0.0",
  "info": {
    "title": "Atlas",
    "version": "1.0.0",
    "description": "Essa é uma documentação sobre a Atlas API."
  },
  "tags": [{ "name": "Users", "description": "Gerenciamento de usuários." }],
  "paths": {
    "/users": {
      "post": {
        "tags": ["Users"],
        "summary": "Criar um novo usuário.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "name": "Yuri Rodrigues da Cunha",
                "email": "yrcunha@gmail.com"
              },
              "schema": {
                "$ref": "#/components/schemas/User_create"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso.",
            "content": {
              "application/json": {
                "example": {
                  "id": "f9471190-c968-4d81-9d8e-75126e1fa4d0",
                  "name": "Yuri Guimarães Rodrigues da Cunha",
                  "email": "yrcunha@gmail.com",
                  "admin": false,
                  "created_at": "2021-03-10T22:10:32.992Z",
                  "updated_at": "2021-03-10T22:10:32.992Z"
                },
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "E-mail já está sendo utilizado.",
            "content": {
              "application/json": {
                "example": {
                  "error": "This Email is already in use."
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users"],
        "summary": "Retorna todos os usuários.",
        "description": "Somente usuário **admin** pode acessas",
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": "f9471190-c968-4d81-9d8e-75126e1fa4d0",
                    "name": "Yuri Guimarães Rodrigues",
                    "email": "yrcunha@gmail.com",
                    "admin": false,
                    "created_at": "2021-03-10T22:10:32.992Z",
                    "updated_at": "2021-03-10T22:10:32.992Z"
                  },
                  {
                    "id": "f9471190-c968-4d81-9d8e-75126e1fa4d0",
                    "name": "Yuri Rodrigues da Cunha",
                    "email": "yuri_rcunha@hotmail.com",
                    "admin": false,
                    "created_at": "2021-03-10T23:10:32.992Z",
                    "updated_at": "2021-03-10T23:10:32.992Z"
                  }
                ],
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "E-mail já está sendo utilizado.",
            "content": {
              "application/json": {
                "example": {
                  "error": "You need to be an administrator to list all user."
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": ["Users"],
        "summary": "Retorna um usuário específico.",
        "parameters": [
          {
            "name": "user_id",
            "required": true,
            "description": "ID do usuário",
            "in": "path",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso.",
            "content": {
              "application/json": {
                "example": {
                  "id": "f9471190-c968-4d81-9d8e-75126e1fa4d0",
                  "name": "Yuri Guimarães Rodrigues",
                  "email": "yrcunha@gmail.com",
                  "admin": false,
                  "created_at": "2021-03-10T22:10:32.992Z",
                  "updated_at": "2021-03-10T22:10:32.992Z"
                },
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "E-mail já está sendo utilizado.",
            "content": {
              "application/json": {
                "example": {
                  "error": "User not found."
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": ["Users"],
        "summary": "Torna admin um usuário.",
        "parameters": [
          {
            "name": "user_id",
            "required": true,
            "description": "ID do usuário",
            "in": "path",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso.",
            "content": {
              "application/json": {
                "example": {
                  "id": "f9471190-c968-4d81-9d8e-75126e1fa4d0",
                  "name": "Yuri Guimarães Rodrigues",
                  "email": "yrcunha@gmail.com",
                  "admin": true,
                  "created_at": "2021-03-10T22:10:32.992Z",
                  "updated_at": "2021-03-10T22:10:32.992Z"
                },
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "Usuário não encontrado.",
            "content": {
              "application/json": {
                "example": {
                  "error": "User not found."
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string",
            "format": "datetime"
          },
          "updated_at": {
            "type": "string",
            "format": "datetime"
          }
        }
      },
      "User_create": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "required": ["name", "email"]
      }
    }
  }
}
